application: 8-bits-live
version: push-07-01-a
runtime: python27
api_version: 1
threadsafe: true


inbound_services:
- channel_presence
- warmup


builtins:
- appstats: on
- remote_api: on


libraries:
- name: pycrypto
  version: "2.3"
- name: django
  version: "1.3"


handlers:

# Various raw files which are only used in debug. Do not upload.
- url: /js/closure/([^\.]+\.js)
  static_files: ../closure/closure/\1
  upload: does_not_exist
- url: /js/bits/([^\.]+\.js)
  static_files: ../frontend/js/bits/\1
  upload: does_not_exist
- url: /tests/([^\.]+\.html)
  static_files: ../frontend/tests/\1
  upload: does_not_exist

# Prefix static files with the current version number to bust caches on push.
- url: /static/[0-9]+/(.+)
  static_files: static/\1
  upload: static

# Task queues serving the user-facing app.
- url: /work/.*
  script: main.APP
  login: admin

# Background jobs and work that is not user-facing.
- url: /jobs/.*
  script: jobs.APP
  login: admin

# Simple debug forms for messing with RPCs.
- url: /admin/debug
  script: main.APP
  login: admin

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin

- url: /_ah/pipeline(/.*)?
  script: mapreduce.main.APP
  login: admin

- url: /.*
  script: main.APP
