application: 8-bits-live
version: push-04-24-a
runtime: python27
api_version: 1
threadsafe: true


inbound_services:
- warmup


builtins:
- appstats: on
- remote_api: on


libraries:
- name: django
  version: "1.3"
- name: pycrypto
  version: "2.3"


handlers:

- url: /admin(/.*)?
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

# Various raw files which are only used in debug. Do not upload.
- url: /js/closure/([^\.]+\.js)
  static_files: ../closure-library/closure/\1
  upload: does_not_exist
- url: /js/bits/([^\.]+\.js)
  static_files: ../frontend/js/bits/\1
  upload: does_not_exist
- url: /tests/([^\.]+\.html)
  static_files: ../frontend/tests/\1
  upload: does_not_exist

# Prefix static files with the current version number to bust caches on push.
- url: /static/[0-9]+/(.+)
  static_files: static/\1
  expiration: 90d
  upload: static
  secure: always

# Static files that need to be at a specific URL with no cache buster.
- url: /robots\.txt
  static_files: static/robots.txt
  expiration: 1s
  upload: static
  secure: always
- url: /favicon\.ico
  static_files: static/favicon.ico
  expiration: 1d
  upload: static
  secure: always
- url: /(trustwave_.*)\.html
  static_files: static/\1.html
  expiration: 0s
  upload: static
  secure: always

# Task queues serving the user-facing app.
- url: /work/.*
  script: main.APP
  login: admin
  secure: always

# Background jobs and work that is not user-facing.
- url: /jobs/.*
  script: jobs.APP
  login: admin
  secure: always

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin
  secure: always

- url: /_ah/pipeline(/.*)?
  script: mapreduce.main.APP
  login: admin
  secure: always

# Everything else is not authenticated.
- url: /.*
  script: main.APP
  secure: always
