application: 8-bits-live
version: push-07-01-a
runtime: python27
api_version: 1
threadsafe: true


inbound_services:
- channel_presence
- warmup


builtins:
- appstats: on


libraries:
- name: pycrypto
  version: "2.3"
- name: django
  version: "1.3"


handlers:
- url: /js/closure/([^\.]+\.js)
  static_files: ../closure/closure/\1
  # Raw Closure files are for debug only. Do not upload.
  upload: does_not_exist

- url: /js/bits/([^\.]+\.js)
  static_files: ../frontend/js/bits/\1
  # Raw Javascript files are for debug only. Do not upload.
  upload: does_not_exist

- url: /tests/([^\.]+\.html)
  static_files: ../frontend/tests/\1
  # Test files are for debug only. Do not upload.
  upload: does_not_exist

- url: /static
  static_dir: static

- url: /work/.*
  script: main.APP
  login: admin

- url: /admin/debug
  script: main.APP
  login: admin

# TODO: Reenable this
# - url: /admin/remote_api
#   login: admin
#   script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py

- url: /.*
  script: main.APP
